package com.example.day05.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.day05.bean.TitleBean;

import com.example.day05.dao.TitleBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig titleBeanDaoConfig;

    private final TitleBeanDao titleBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        titleBeanDaoConfig = daoConfigMap.get(TitleBeanDao.class).clone();
        titleBeanDaoConfig.initIdentityScope(type);

        titleBeanDao = new TitleBeanDao(titleBeanDaoConfig, this);

        registerDao(TitleBean.class, titleBeanDao);
    }
    
    public void clear() {
        titleBeanDaoConfig.clearIdentityScope();
    }

    public TitleBeanDao getTitleBeanDao() {
        return titleBeanDao;
    }

}
